name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install requirements
      run: |
        sudo apt-get install pylint
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Verify
      run: |
        source env/bin/activate
        pylint bingo.py bingo_test.py
    - name: Run test
      run: |
        source env/bin/activate
        python -m unittest bingo_test